# early stopping - whatever is triggered first
max_epochs: 100_000_000
max_env_steps: 500_000_000
# model params
device: 'cuda'  # 'cuda' or 'cpu'
input_dim: 569  # == len(AugmentObservationFeatureColumns)
# FOLD, CHECK_CALL, RAISE
output_dim: 3  # 1<= output_dim <= len(ActionSpace)
# nn params
lrs:
  - 1e-6
hdims:
  - (512, 512)
  - 512
batch_size: 512
# progress
log_interval: 500  # log every `n` batches of size `batch_size`
eval_interval: 1000  # log every `n` batches of size `batch_size`
debug: False