#dataset_configs:
#  - PFTR_no_folds_all_showdowns_with_hudstats_ActionSpace
# early stopping - whatever is triggered first
max_epochs: 10_000
max_env_steps: 100_000_000_000
# model params
device: 'cuda'  # 'cuda' or 'cpu'
# input_dim: 569  # == len(AugmentObservationFeatureColumns)
input_dim: 588  # == len(AugmentObservationFeatureColumns)
# FOLD, CHECK_CALL, RAISE
output_dim: 7  # 1<= output_dim <= len(ActionSpace)
#target_names_full = ['Fold',
#                     'Check Call',
#                     'Raise Third Pot',
#                     'Raise Two Thirds Pot',
#                     'Raise Pot',
#                     'Raise 2x Pot',
#                     'Raise 3x Pot',
#                     'Raise All in']
#target_names_full_no_fold = [
#    'Check Call',
#    'Raise Third Pot',
#    'Raise Two Thirds Pot',
#    'Raise Pot',
#    'Raise 2x Pot',
#    'Raise 3x Pot',
#    'Raise All in']
#target_names = ['Fold',
#                'Check Call',
#                'Raise']
label_names: # examples above
  - Check_Call,
  - Raise_Third_Pot,
  - Raise_Two_Thirds_Pot',
  - Raise_Pot,
  - Raise_2x_Pot,
  - Raise_3x_Pot,
  - Raise_All_in
labels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
# nn params
lrs:
  - 1e-6
hdims:
  - 512
batch_size: 256
# progress
log_interval: 500  # log every `n` batches of size `batch_size`
eval_interval: 1000  # log every `n` batches of size `batch_size`
debug: False